# Cursor Rules — AI Coding Assistant Instructions
# Generated by skill_exporter.py — do not edit manually.
# Re-run: python tools/skill_exporter.py --target cursor

You are an expert software engineer. Follow these technology-specific standards when writing or reviewing code in this repository.

## Apache Camel Advanced Skill (java, apache-camel, spring-boot, integration, eip)

# Apache Camel Advanced Skill — v1.0

---

## 1. Core Concepts (Mental Model First)

Understanding Camel starts with four objects that flow through every route:

```java
Exchange  — the wrapper that carries a message through a route
  └── Message (IN)   — the current message being processed
        ├── Body     — the payload (String, byte[], POJO, InputStream, etc.)
        ├── Headers  — key/value metadata (like HTTP headers, file names, etc.)
        └── Properties — exchange-scoped metadata (survive routing steps)
```java

**Route** = a pipeline of steps. Data enters at a `from()`, flows through
processors and transformers, and exits at one or more `to()` endpoints.

**Component** = a connector to an external system (file, HTTP, Kafka, DB, etc.).
A component creates **Endpoints**. An endpoint creates **Producers** (send) and
**Consumers** (receive).

**Processor** = a single processing step. Receives an `Exchange`, modifies it,
passes it on.

---

## 2. Route DSL — Java (Primary)

### Basic Route Structure

```java
import org.apache.camel.builder.RouteBuilder;

/**
 * Processes incoming orders from a file drop folder.
 *
 * <p>Reads JSON files from /data/orders/incoming, validates them,
 * transforms to the internal format, and sends to the order-processing queue.
 * Failed files are moved to /data/orders/error.</p>
 */
@Component
public class OrderIngestionRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {

        // ── Global erro

---

## Apache Pulsar Advanced Skill (java, python, apache-pulsar, spring-boot, messaging, streaming)

## 1. Architecture Mental Model

```java
Pulsar Cluster
  ├── Broker(s)        — stateless, route messages; can scale horizontally
  ├── BookKeeper       — durable message storage (write-ahead log)
  └── ZooKeeper        — metadata, broker coordination

Topic naming:
  persistent://  {tenant} / {namespace} / {topic-name}
  Example:       persistent://orders/payments/card-transactions

  persistent://  → messages survive broker restart (backed by BookKeeper)
  non-persistent:// → messages lost if broker restarts (high throughput, low durability)
```java

### Key Concepts vs Kafka

| Concept | Kafka | Pulsar |
|---------|-------|--------|
| Message storage | Broker (stateful) | BookKeeper (separate) |
| Consumer model | Consumer Group | Subscription (4 types) |
| Rebalancing | Required on membership change | Not needed (per-message ack) |
| Multi-tenancy | Manual (naming convention) | Built-in (tenant/namespace) |
| Schema | Schema Registry (separate) | Built-in Schema Registry |
| Geo-replication | MirrorMaker2 | Built-in |

---

## 2. Producers

### Java Producer (Spring for Apache Pulsar)

```java
import org.springframework.pulsar.core.PulsarTemplate;

/**
 * Publishes order events to the Pulsar order-events topic.
 *
 * <p>Uses Spring's {@link PulsarTemplate} — the Spring-managed, lifecycle-aware
 * wrapper around the Pulsar client. Always prefer PulsarTemplate over creating
 * PulsarClient directly in Spring apps.</p>
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class OrderEventPublisher {

    private final PulsarTemplate<OrderEvent> pulsarTemplate;

    // Topic name — use a constant to avoid typos across the codebase
    private static final String ORDER_EVENTS_TOPIC = "persistent://orders/default/order-events";

    /**
     * Publishes an order created event.
     *
     * <p>This is a fire-and-forget send — the method returns immediately.
     * Use {@link #publishAndWait} if you need confirmation before continuing.</p>
     *
     * @param event the
---

## Apache Camel Exception Handling & Routing Skill (java, apache-camel, spring-boot, integration, error-handling)

## 1. Exception Handler in Camel Routes

### 1.1 Global Exception Handler

```java
/**
 * Configure global exception handlers for all routes.
 *
 * Catches exceptions and routes them to error processing endpoints.
 */
@Configuration
public class CamelExceptionConfig implements RoutesBuilder {

    @Override
    public void addRoutes(RouteBuilder builder) throws Exception {
        // Global exception handler
        builder.onException(Exception.class)
                .handled(true)
                .maximumRedeliveries(3)
                .redeliveryDelay(1000)
                .backOffMultiplier(2.0)
                .log("Global error handler caught: ${exception.message}")
                .to("direct:errorHandler");

        // Specific exception handler: Business validation errors
        builder.onException(ValidationException.class)
                .handled(true)
                .maximumRedeliveries(0)  // Don't retry validation errors
                .log("Validation error: ${body}")
                .setBody(constant(new ErrorResponse(
                    "VALIDATION_ERROR",
                    "Request validation failed",
                    400
                )))
                .to("direct:sendErrorResponse");

        // Specific exception handler: Transient failures (network, timeout)
        builder.onException(TimeoutException.class, ConnectException.class)
                .handled(false)  // Don't suppress exception, let caller handle
                .maximumRedeliveries(5)
                .redeliveryDelay(500)
                .backOffMultiplier(1.5)
                .log("Transient error, retrying: ${exception.message}");

        // Specific exception handler: Database errors
        builder.onException(SQLException.class)
                .handled(true)
                .maximumRedeliveries(2)
                .redeliveryDelay(2000)
                .log("Database error: ${exception.message}")
                .to("direct:notifyDatabaseTeam");
    }
}
```ja
---

## Apache Camel & Pulsar Integration Skill (java, apache-camel, apache-pulsar, integration, spring-boot, messaging)

## 1. Camel-Pulsar Component Overview

### 1.1 Maven Dependency

```xml
<dependency>
    <groupId>org.apache.camel.springboot</groupId>
    <artifactId>camel-pulsar-starter</artifactId>
    <version>4.0.0</version>
</dependency>

<dependency>
    <groupId>org.apache.pulsar</groupId>
    <artifactId>pulsar-client</artifactId>
    <version>3.0.0</version>
</dependency>
```

### 1.2 Camel Pulsar URI Scheme

```java
// Consumer: Read from Pulsar topic
from("pulsar:persistent://public/default/my-topic"
    + "?numberOfConsumers=1"
    + "&subscriptionName=my-subscription"
    + "&subscriptionType=EXCLUSIVE"
)
.to("direct:processMessage");

// Producer: Send to Pulsar topic
from("direct:sendMessage")
    .to("pulsar:persistent://public/default/my-topic"
        + "?numberOfProducers=1"
        + "&compressionType=LZ4"
    );
```

---

## 2. Consumer Patterns with Camel

### 2.1 Simple Topic Consumer

```java
/**
 * Simple Pulsar consumer route with Camel.
 */
@Configuration
public class PulsarConsumerRoute extends RouteBuilder {

    @Override
    public void configure() throws Exception {
        from("pulsar:persistent://public/default/orders"
                + "?numberOfConsumers=5"
                + "&subscriptionName=order-processor"
                + "&subscriptionType=SHARED"
                + "&acknowledgeInterval=1000")
                .log("Received message: ${body}")
                .process(exchange -> {
                    String message = exchange.getIn().getBody(String.class);
                    OrderEvent order = parseOrder(message);
                    exchange.setProperty("orderId", order.getId());
                })
                .to("direct:processOrder");

        from("direct:processOrder")
                .log("Processing order: ${property.orderId}")
                .to("bean:orderService?method=process");
    }

    private OrderEvent parseOrder(String json) {
        // Parse JSON to OrderEvent
        return new ObjectMapper().readValue(json, 
---

## Code Formatting & Style Skill (java, python, javascript, typescript, code-quality, formatting)

## 1. Universal Formatting Rules
---

## Code Health Inspection Skill (java, python, react, mssql, all-languages)

## 1. Issue Taxonomy

Every issue found during a scan belongs to one of these seven categories.
Use these category codes in the report.

| Code | Category | Examples |
|------|----------|---------|
| `PERF` | Performance & Slowness | N+1 queries, missing indexes, blocking calls, over-fetching, missing pagination |
| `ERR` | Error Handling | Swallowed exceptions, missing try/catch, no fallback, bare `except`, silent failures |
| `DELAY` | Processing Delays | Synchronous calls that should be async, missing queues, retry storms, no timeouts |
| `MEM` | Memory & Resource Leaks | Unclosed connections, unbounded caches, large objects in memory, no streaming |
| `SEC` | Security | SQL injection, hardcoded secrets, insecure deserialization, missing auth checks |
| `MAINT` | Maintainability | God classes, deeply nested code, magic numbers, missing documentation, dead code |
| `RELI` | Reliability | No retry logic, no circuit breaker, missing health checks, no idempotency |

---

## 2. Severity Scale

Assign one severity level to each issue found.

| Level | Code | Meaning | Action |
|-------|------|---------|--------|
| Critical | `P0` | Causes data loss, outages, or security breaches in production | Fix before next deploy |
| High | `P1` | Causes user-visible failures or significant performance degradation | Fix in current sprint |
| Medium | `P2` | Causes intermittent issues or technical debt that will compound | Fix in next sprint |
| Low | `P3` | Code smell, maintainability concern, minor inefficiency | Fix when touching this code |

---

## 3. Evidence Collection Rules

For each issue found, you MUST collect:

1. **Location** — exact file, class, method, and line number (or range)
2. **Evidence** — the exact code snippet that demonstrates the problem
3. **Root Cause** — WHY this is a problem (not just what it is)
4. **Impact** — what can go wrong at runtime because of this
5. **Fix** — a concrete code example showing the corrected version

Never report a vague issue lik
---

## Code Documentation & Comments Skill (java, python, javascript, typescript, documentation, code-quality)

## 1. File Headers with Author & Date

### 1.1 Java File Header

```java
/**
 * Order processing service for managing order lifecycle.
 *
 * <p>Handles order creation, validation, payment processing, and fulfillment.
 * This service is the main entry point for order operations.</p>
 *
 * <p><b>Author:</b> John Doe</p>
 * <p><b>Date:</b> 2026-04-03</p>
 * <p><b>Version:</b> 2.0</p>
 * <p><b>Last Modified:</b> 2026-04-03 by John Doe</p>
 *
 * @author John Doe (john@example.com)
 * @version 2.0
 * @since 1.0
 */
package com.example.orders.services;

import java.time.LocalDateTime;
import java.util.List;

public class OrderService {
    // Class content
}
```plaintext

### 1.2 Python File Header

```python
"""
Order processing service for managing order lifecycle.

Handles order creation, validation, payment processing, and fulfillment.
This service is the main entry point for order operations.

Author: John Doe (john@example.com)
Date: 2026-04-03
Version: 2.0
Last Modified: 2026-04-03 by John Doe

Attributes:
    logger: Configured logger instance for this module.
"""

__author__ = "John Doe"
__email__ = "john@example.com"
__date__ = "2026-04-03"
__version__ = "2.0"

import logging
from typing import Optional, List

logger = logging.getLogger(__name__)


class OrderService:
    """Order processing service."""
```plaintext

### 1.3 JavaScript/TypeScript File Header

```typescript
/**
 * Order processing service for managing order lifecycle.
 *
 * Handles order creation, validation, payment processing, and fulfillment.
 * This service is the main entry point for order operations.
 *
 * @author John Doe <john@example.com>
 * @version 2.0
 * @since 1.0
 * @date 2026-04-03
 * @lastModified 2026-04-03 by John Doe
 */

import { OrderRepository } from './repositories/OrderRepository';
import { PaymentGateway } from './gateways/PaymentGateway';

export class OrderService {
  // Class content
}
```plaintext

---

## 2. Javadoc Standard (Java)

### 2.1 Class Documentation

```jav
---

## Error Handling & Resilience Skill (java, python, javascript, react, error-handling, exceptions)

## 1. Exception Design Principles

### 1.1 Custom Exception Hierarchy

```java
// Java: Create custom exceptions with clear semantics

/**
 * Base exception for all domain errors in the order system.
 *
 * <p>All domain-specific exceptions inherit from this, making it easy to catch
 * all business errors while letting system errors propagate.</p>
 */
public abstract class DomainException extends RuntimeException {

    private final String errorCode;

    public DomainException(String errorCode, String message) {
        super(message);
        this.errorCode = errorCode;
    }

    public DomainException(String errorCode, String message, Throwable cause) {
        super(message, cause);
        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
    }
}

/**
 * Thrown when a required entity is not found.
 */
public class EntityNotFoundException extends DomainException {
    public EntityNotFoundException(String entityType, Object id) {
        super("ENTITY_NOT_FOUND",
              String.format("%s not found: %s", entityType, id));
    }
}

/**
 * Thrown when business rule validation fails.
 */
public class ValidationException extends DomainException {
    public ValidationException(String message) {
        super("VALIDATION_ERROR", message);
    }
}

/**
 * Thrown when operation cannot proceed due to resource constraints.
 */
public class InsufficientResourcesException extends DomainException {
    public InsufficientResourcesException(String resource) {
        super("INSUFFICIENT_RESOURCES",
              String.format("Insufficient %s available", resource));
    }
}

/**
 * Thrown when operation conflicts with existing state.
 */
public class ConflictException extends DomainException {
    public ConflictException(String message) {
        super("CONFLICT", message);
    }
}
```plaintext

```python
# Python: Create custom exception hierarchy

class DomainException(Exception):
    """
    Base exception for all doma
---

## Java 11 Long-Term Support & Production Features (java, java-11, spring-boot, production, best-practices)

## 1. Java 11 LTS Overview

### 1.1 Release Information

```
Java 11 (September 2018)
├── LTS: Supported until September 2026
├── Next LTS: Java 17 (September 2021)
├── Recommended: Use for production systems
├── Version: 11.0.x with regular updates
└── Recommended for: New projects, migration targets
```

**Major Features:**
- Local variable syntax (var)
- HTTP Client (new standard)
- Module system finalized
- String methods (strip, isBlank)
- Stream improvements
- Single-file source code execution
- Performance improvements

---

## 2. Local Variable Syntax — var Keyword

### 2.1 Basic var Usage

```java
/**
 * var: Infer type from assigned value.
 * Reduces boilerplate without losing type safety.
 */
public class VarKeyword {

    // ✗ OLD: Explicit type declaration
    public void oldWay() {
        String message = "Hello World";
        List<Order> orders = new ArrayList<>();
        Map<String, Customer> customerMap = new HashMap<>();
        Iterator<Order> iterator = orders.iterator();
    }

    // ✓ NEW: Type inference with var
    public void newWay() {
        var message = "Hello World";                          // String
        var orders = new ArrayList<Order>();                 // List<Order>
        var customerMap = new HashMap<String, Customer>();   // Map<String, Customer>
        var iterator = orders.iterator();                     // Iterator<Order>
    }

    // Type is still inferred: Compile error if used incorrectly
    public void typeCheckingStillWorks() {
        var number = 42;                                      // int
        // number = "string";  // ✗ Compile error: incompatible types
    }
}
```

### 2.2 var in Collections & Streams

```java
/**
 * var with collections and streams.
 */
public class VarWithCollections {

    public void processOrders(List<Order> orders) {
        // var in for-each loop
        for (var order : orders) {
            System.out.println(order.getId());
        }

        // var with stream proces
---

## Java 17 Modern Features & Best Practices (java, java-17, spring-boot, best-practices, patterns)

## 1. Java 17 Release Overview

### 1.1 Long-Term Support (LTS)

```
Java 17 (September 2021)
├── LTS Release: Supported until September 2026
├── Next LTS: Java 21 (September 2023)
└── Recommended: Use for production systems
```

**Key Features Added:**
- Records (JEP 395)
- Sealed Classes (JEP 409)
- Pattern Matching for switch (JEP 406)
- Text Blocks (JEP 378)
- Removed legacy APIs
- Module system refinements

---

## 2. Records — Immutable Data Carriers

### 2.1 Basic Record Syntax

```java
/**
 * Record: Immutable data carrier with generated equals/hashCode/toString.
 */
public record Order(
        Long id,
        Long customerId,
        BigDecimal amount,
        String status) {
    // Compact record: 5 lines replaces 50 lines of boilerplate
}

// Usage:
Order order = new Order(1L, 100L, BigDecimal.valueOf(99.99), "PENDING");
System.out.println(order);  // Order[id=1, customerId=100, amount=99.99, status=PENDING]
System.out.println(order.id());  // 1 (accessor methods auto-generated)
```

### 2.2 Record with Validation

```java
/**
 * Record with custom validation in compact constructor.
 */
public record Money(
        BigDecimal amount,
        String currency) {

    // Compact constructor: Implicit parameters, runs before field assignment
    public Money {
        if (amount == null || amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Amount must be non-negative");
        }
        if (currency == null || currency.isEmpty()) {
            throw new IllegalArgumentException("Currency is required");
        }
        // Fields are assigned after validation
    }
}

// Usage:
Money validMoney = new Money(BigDecimal.valueOf(100), "USD");
// Money invalidMoney = new Money(BigDecimal.valueOf(-10), "USD");  // Throws exception
```

### 2.3 Record with Custom Methods

```java
/**
 * Record with additional methods and derived fields.
 */
public record OrderItem(
        Long productId,
        int quantity,
        BigDec
---

## Java Advanced Coding Skill (java, spring-boot, maven, gradle)

## 1. Version Detection First

Before writing any Java code, check what is installed:

```bash
java -version
mvn -version
```java

Then match features to what is available:

| Java Version | Use These Features |
|-------------|-------------------|
| Java 11 | `var`, HTTP Client, `Optional`, lambda, streams |
| Java 17 (LTS) | All above + **records**, **sealed classes**, **text blocks**, switch expressions |
| Java 21 (LTS) | All above + **virtual threads** (`Thread.ofVirtual()`), **pattern matching for switch**, sequenced collections |

---

## 2. Four OOP Pillars — Applied in Java

### 2.1 Encapsulation — Control What Can Change

Keep fields private. Provide controlled access through methods.

```java
/**
 * Represents a customer's bank account.
 *
 * <p>Balance can only change through deposit() and withdraw().
 * Direct field access is not allowed outside this class.</p>
 */
public class BankAccount {

    /** The account owner's full name. Immutable after creation. */
    private final String ownerName;

    /** Current balance in the account currency. Modified only via transactions. */
    private double balance;

    /**
     * Creates a new bank account.
     *
     * @param ownerName     the full name of the account holder
     * @param initialBalance starting balance — must be zero or positive
     * @throws IllegalArgumentException if initialBalance is negative
     */
    public BankAccount(String ownerName, double initialBalance) {
        if (initialBalance < 0) {
            throw new IllegalArgumentException(
                "Initial balance cannot be negative. Got: " + initialBalance
            );
        }
        this.ownerName = ownerName;
        this.balance   = initialBalance;
    }

    /**
     * Deposits money into the account.
     *
     * @param amount amount to deposit — must be positive
     * @throws IllegalArgumentException if amount is zero or negative
     */
    public void deposit(double amount) {
        if (amount <= 0) {
      
---

## Logging Best Practices & Implementation (java, logging, slf4j, log4j2, logback, spring-boot)

## 1. Logging Architecture Overview

### 1.1 Logging Stack Layers

```
┌─────────────────────────────────────────────┐
│  Application Code (Log Statements)          │
├─────────────────────────────────────────────┤
│  SLF4J / Commons Logging / JUL (Facade)    │  ← Abstraction layer
├─────────────────────────────────────────────┤
│  Logback / Log4j2 / Log4j (Implementation)  │  ← Actual logging
├─────────────────────────────────────────────┤
│  Appenders (Console, File, Network)         │  ← Output targets
├─────────────────────────────────────────────┤
│  Layouts/Patterns (Format log messages)     │  ← Message format
└─────────────────────────────────────────────┘
```

**Best Practice:** Use SLF4J as facade + Logback as implementation.

---

## 2. SLF4J — The Logging Facade

### 2.1 SLF4J with Logback (Recommended)

```xml
<!-- Maven: SLF4J with Logback -->
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>2.0.7</version>
</dependency>

<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.4.11</version>
</dependency>

<!-- Exclude commons-logging if present -->
<dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <scope>provided</scope>
</dependency>
```

### 2.2 Basic SLF4J Usage

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class OrderService {

    private static final Logger logger = LoggerFactory.getLogger(OrderService.class);

    public void processOrder(Order order) {
        // Log at different levels
        logger.debug("Processing order: {}", order.getId());
        logger.info("Order started for customer: {}", order.getCustomerId());

        try {
            // Process order
            saveOrder(order);
            logger.info("Order {} saved successfully", order.getId());

        } catch (Exception e) {
            logger.error("Failed to process order {}: {}", order.ge
---

## Project Lombok Skill (java, lombok, spring-boot, maven, gradle, code-generation)

## 1. Maven & Gradle Setup

### 1.1 Maven Configuration

```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.30</version>
    <scope>provided</scope>
</dependency>

<!-- Maven compiler plugin configuration -->
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.10.1</version>
    <configuration>
        <source>17</source>
        <target>17</target>
        <annotationProcessorPaths>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.30</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```

### 1.2 Gradle Configuration

```gradle
dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}
```

### 1.3 IDE Configuration

```
IntelliJ IDEA:
  Settings → Plugins → Search "Lombok" → Install
  Settings → Build, Execution, Deployment → Compiler →
    Annotation Processors → Enable annotation processing

VS Code:
  Install "Lombok Annotations Support for VS Code"
  Install "Language Support for Java (Red Hat)"

Eclipse:
  Run: java -jar lombok.jar install eclipse.exe
```

---

## 2. Core Annotations

### 2.1 @Getter & @Setter

```java
/**
 * Generate getters and setters automatically.
 */
@Getter
@Setter
public class Order {
    private Long id;
    private Long customerId;
    private BigDecimal totalAmount;
    private String status;

    // Generates:
    // public Long getId() { return this.id; }
    // public void setId(Long id) { this.id = id; }
    // ... for all fields
}

/**
 * Selective generation: @Getter on class, @Setter on field.
 */
@Getter
public class ImmutableOrder {
    private Long id;
    private Long customerId;
    private BigDecimal totalAmount;

    @Setter
    private String status;  // Only this field has
---

## MSSQL Advanced Coding Skill (mssql, t-sql, sql-server, azure-sql)

## 1. Version Detection First

Before writing any SQL, check what is installed:

```sql
-- Run this and share the output
SELECT @@VERSION;
SELECT SERVERPROPERTY('ProductVersion') AS [Version],
       SERVERPROPERTY('Edition')        AS [Edition];
```sql

| Version | Key Features Available |
|---------|----------------------|
| SQL Server 2016 | JSON support, `STRING_SPLIT`, temporal tables |
| SQL Server 2017 | `STRING_AGG`, Graph tables, cross-platform (Linux) |
| SQL Server 2019 | `APPROX_COUNT_DISTINCT`, Accelerated Database Recovery (ADR), UTF-8 support |
| SQL Server 2022 | `IS [NOT] DISTINCT FROM`, ledger tables, improved JSON, Azure Synapse Link |
| Azure SQL | Always latest — auto-patched, serverless option, hyperscale |

---

## 2. NOLOCK — Explained Simply

This is one of the most misunderstood hints in T-SQL. Understand it before using it.

### What NOLOCK Does

```sql
-- NOLOCK = READ UNCOMMITTED isolation level
-- Translation: "Read data even if another transaction is actively changing it."
--
-- SQL Server normal behaviour (READ COMMITTED):
--   Reader waits for Writer to finish and commit. Safe, but can block.
--
-- NOLOCK behaviour:
--   Reader does NOT wait. Reads the data as it is right now —
--   even if the writing transaction hasn't committed yet
--   (or might roll back).

-- Example of the risk — a dirty read:
-- Transaction A: starts updating order #99 (balance was £500, now writing £200)
-- Transaction B (with NOLOCK): reads order #99 and sees £200
-- Transaction A: gets an error, rolls back — balance goes back to £500
-- Transaction B now has a "fact" (£200) that was never true. It never committed.
```sql

### Decision Guide — NOLOCK or Not?

```sql
Is this query used for financial calculations, balances, or totals?
  YES → ❌ Never use NOLOCK. Use RCSI instead.

Is this query used for order status that drives a business decision?
  YES → ❌ Never use NOLOCK. Use RCSI instead.

Is this a dashboard or report where approximate counts are accept
---

## Object-Oriented Programming (OOP) Skill (java, python, javascript, oop, design-patterns, solid)

## 1. Encapsulation — Data Hiding & Control

**Goal:** Hide internal details, expose only what's necessary.

### 1.1 Encapsulation in Java

```java
/**
 * ✗ WRONG: Public fields expose internal state
 */
public class BadBankAccount {
    public String accountNumber;
    public BigDecimal balance;
    public List<Transaction> transactions;

    // Anyone can directly modify these, breaking invariants
}

/**
 * ✓ CORRECT: Private fields + controlled access
 */
public class BankAccount {
    // Private: Only this class can access
    private final String accountNumber;
    private BigDecimal balance;
    private final List<Transaction> transactions = new ArrayList<>();

    public BankAccount(String accountNumber, BigDecimal initialBalance) {
        this.accountNumber = accountNumber;
        this.balance = initialBalance;
    }

    // Public API: Controlled access
    public String getAccountNumber() {
        return accountNumber;  // Read-only
    }

    public BigDecimal getBalance() {
        return balance;  // Current state
    }

    public void deposit(BigDecimal amount) {
        if (amount.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("Deposit must be positive");
        }
        balance = balance.add(amount);
        transactions.add(new Transaction("DEPOSIT", amount));
    }

    public void withdraw(BigDecimal amount) {
        if (amount.compareTo(balance) > 0) {
            throw new InsufficientFundsException("Not enough balance");
        }
        balance = balance.subtract(amount);
        transactions.add(new Transaction("WITHDRAW", amount));
    }

    public List<Transaction> getTransactionHistory() {
        // Return unmodifiable copy, not the original list
        return Collections.unmodifiableList(transactions);
    }
}
```

### 1.2 Encapsulation in Python

```python
class BankAccount:
    """
    Encapsulation example in Python.

    Private attributes use name mangling (_BankAccount__balance).
    Pro
---

## OpenTelemetry Observability & Distributed Tracing (java, observability, tracing, metrics, opentelemetry, spring-boot)

## 1. OpenTelemetry Overview

### 1.1 Three Pillars of Observability

```
┌─────────────────────────────────────────────────────────┐
│  OBSERVABILITY = Traces + Metrics + Logs                │
├─────────────────────────────────────────────────────────┤
│                                                          │
│  TRACES: Request flow through distributed system       │
│  ├─ Span: Single operation (HTTP request, DB query)    │
│  ├─ Trace ID: Correlate spans across services          │
│  └─ Baggage: Context passed between services           │
│                                                          │
│  METRICS: Numerical measurements (counters, gauges)    │
│  ├─ Request count, latency, error rate                │
│  ├─ JVM memory, CPU, thread count                      │
│  └─ Business metrics (orders/sec, revenue)             │
│                                                          │
│  LOGS: Structured text events                          │
│  ├─ Application logs                                   │
│  ├─ Correlation with traces via trace IDs              │
│  └─ Machine-readable JSON format                       │
│                                                          │
└─────────────────────────────────────────────────────────┘
```

### 1.2 OpenTelemetry Architecture

```
Application Code
        ↓
   OpenTelemetry API (Facade)
        ↓
   OpenTelemetry SDK (Implementation)
        ↓
   Exporters (Jaeger, Prometheus, OTLP)
        ↓
   Backend (Jaeger, Prometheus, ELK, DataDog, etc.)
```

---

## 2. Maven Setup & Dependencies

### 2.1 OpenTelemetry Dependencies

```xml
<!-- OpenTelemetry BOM: Manage all versions consistently -->
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-bom</artifactId>
            <version>1.35.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyMana
---

## Python Advanced Coding Skill (python, fastapi, sqlalchemy, pydantic, asyncio)

## 1. Version Detection First

Before writing any Python code, check what is installed:

```bash
python --version   # or: python3 --version
pip --version
```python

| Python Version | Features Available |
|---------------|--------------------|
| 3.10 | `match` statement, `X \| Y` union types (in annotations only) |
| 3.11 | ~60% faster, `tomllib`, `ExceptionGroup`, `Self` type |
| 3.12 | `@override` decorator, `type` alias statement, better f-strings |
| 3.13 | Free-threaded mode (experimental), improved REPL |

**Default target:** Python 3.11 features unless a higher version is confirmed.

---

## 2. Four OOP Pillars — Applied in Python

### 2.1 Encapsulation — Properties and Private Attributes

Python uses naming convention (`_name`) and `@property` for encapsulation.

```python
class BankAccount:
    """Represents a customer bank account.

    The balance is private — it can only be changed through
    deposit() and withdraw() methods, not set directly from outside.

    Attributes:
        owner_name: The name of the account holder.
    """

    def __init__(self, owner_name: str, initial_balance: float = 0.0) -> None:
        """Creates a new bank account.

        Args:
            owner_name: Full name of the account holder.
            initial_balance: Starting balance. Must be zero or positive.

        Raises:
            ValueError: If initial_balance is negative.
        """
        if initial_balance < 0:
            raise ValueError(
                f"Initial balance cannot be negative. Got: {initial_balance}"
            )
        self._owner_name = owner_name          # _name = private by convention
        self._balance    = initial_balance

    @property
    def balance(self) -> float:
        """The current account balance. Can be read but not set directly."""
        return self._balance

    @property
    def owner_name(self) -> str:
        """The account holder's name. Read-only."""
        return self._owner_name

    def deposit(self, amount
---

## React Advanced Coding Skill (react, typescript, vite, tanstack-query, zustand, tailwindcss)

## 1. Version Detection First

Check what is installed before writing code:

```bash
node -v
cat package.json | grep '"react"'
cat package.json | grep '"typescript"'
```jsx

| React Version | Key Features |
|--------------|-------------|
| React 17 | Stable, no concurrent features |
| React 18 | Concurrent rendering, `useTransition`, `useDeferredValue`, `Suspense` for data |
| React 19 | `use()` hook, `useFormStatus`, `useOptimistic`, Server Actions |

---

## 2. Component Design Principles

### One Component = One Job

Each component should do exactly one thing. If it does more, split it.

```jsx
❌ UserDashboard — renders layout, fetches data, shows charts, handles modals
✅ UserDashboard  — layout only
✅ useUserStats   — fetches the data (custom hook)
✅ StatsChart     — renders one chart
✅ UserModal      — one modal
```jsx

### Component File Structure

Every non-trivial component lives in its own folder:

```jsx
features/orders/
  components/
    OrderCard/
      OrderCard.tsx         ← the component
      OrderCard.test.tsx    ← the tests
      index.ts              ← export: export { OrderCard } from './OrderCard'
  hooks/
    useOrders.ts            ← TanStack Query hook
  types/
    order.types.ts          ← TypeScript types for orders
```jsx

---

## 3. TypeScript — Always Strict

### Typed Props with JSDoc (Documentation)

Every exported component must have a named interface for its props, with JSDoc:

```tsx
/**
 * Displays a summary card for a single customer order.
 *
 * Shows the order ID, current status (colour-coded), and formatted total.
 * Clicking the card triggers the onClick handler.
 *
 * @example
 * <OrderCard
 *   orderId={42}
 *   status="SHIPPED"
 *   totalAmount={99.99}
 *   currency="GBP"
 *   onClick={(id) => navigate(`/orders/${id}`)}
 * />
 */
interface OrderCardProps {
  /** Unique identifier for this order. */
  orderId: number;

  /** Current status of the order. Determines the badge colour. */
  status: 'PENDING' | 'CONFIRMED' | 'SHI
---

## REST API Java Skill (java, spring-boot, rest-api, http, maven)

## 1. HTTP Method Design & Semantics

Match HTTP verbs to actions correctly:

| Method | Purpose | Idempotent | Safe | Response Body |
|--------|---------|-----------|------|----------------|
| **GET** | Retrieve resource(s) | ✓ | ✓ | Resource data |
| **POST** | Create new resource | ✗ | ✗ | Created resource + location |
| **PUT** | Replace entire resource | ✓ | ✗ | Updated resource |
| **PATCH** | Partial update | ✗ | ✗ | Updated resource |
| **DELETE** | Remove resource | ✓ | ✗ | Empty (204) or confirmation |
| **HEAD** | Like GET, no body | ✓ | ✓ | None (metadata only) |

**Anti-pattern:** `POST /api/orders/123/cancel` → Instead use `DELETE /api/orders/123` or `PATCH /api/orders/123` with `{"status": "cancelled"}`

---

## 2. Status Codes — Return the Right One

```java
// 2xx: Success
200 OK           // GET, PUT, PATCH successful
201 Created      // POST created resource
202 Accepted     // Async operation started
204 No Content   // DELETE, no response body

// 3xx: Redirection
301 Moved Permanently
302 Found / Temporary Redirect

// 4xx: Client error
400 Bad Request     // Validation failed, malformed JSON
401 Unauthorized    // Missing/invalid auth
403 Forbidden       // Authenticated but no permission
404 Not Found       // Resource doesn't exist
409 Conflict        // Version mismatch, concurrent update
422 Unprocessable   // Semantically invalid

// 5xx: Server error
500 Internal Server Error
503 Service Unavailable
```java

---

## 3. REST Controller Pattern — Spring Boot

```java
/**
 * REST API endpoint for managing customer orders.
 *
 * <p>Handles order creation, retrieval, updates, and cancellation.
 * All endpoints require Bearer token authentication.</p>
 */
@RestController
@RequestMapping("/api/v1/orders")
@RequiredArgsConstructor
public class OrderRestController {

    private final OrderService orderService;
    private final OrderMapper orderMapper;

    /**
     * GET /api/v1/orders — List all orders with pagination.
     *
     * @param pag
---

## REST API Python Skill (python, fastapi, rest-api, http, async)

## 1. FastAPI Project Structure

```plaintext
project/
├── app/
│   ├── __init__.py
│   ├── main.py                 # FastAPI app initialization
│   ├── config.py              # Settings & environment
│   ├── dependencies.py        # Shared dependencies (DB session, auth)
│   │
│   ├── api/
│   │   ├── __init__.py
│   │   ├── v1/
│   │   │   ├── __init__.py
│   │   │   ├── orders.py      # Order endpoints
│   │   │   ├── customers.py   # Customer endpoints
│   │   │   └── router.py      # Combine all v1 routers
│   │   │
│   │   └── v2/
│   │       ├── __init__.py
│   │       └── router.py
│   │
│   ├── models/                # SQLAlchemy models
│   │   ├── __init__.py
│   │   ├── order.py
│   │   └── customer.py
│   │
│   ├── schemas/               # Pydantic request/response schemas
│   │   ├── __init__.py
│   │   ├── order.py
│   │   └── customer.py
│   │
│   ├── services/              # Business logic
│   │   ├── __init__.py
│   │   ├── order_service.py
│   │   └── customer_service.py
│   │
│   ├── repository/            # Data access
│   │   ├── __init__.py
│   │   ├── order_repo.py
│   │   └── customer_repo.py
│   │
│   └── exceptions/            # Custom exceptions
│       ├── __init__.py
│       └── handlers.py
│
├── tests/
│   ├── conftest.py
│   ├── test_orders.py
│   └── test_customers.py
│
├── .env
├── requirements.txt
└── pyproject.toml
```python

---

## 2. FastAPI App Initialization

```python
"""
Main FastAPI application factory.

Author: Your Name
Date: 2026-04-03
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.exceptions import RequestValidationError

from app.api.v1.router import api_router_v1
from app.exceptions.handlers import validation_exception_handler
from app.config import settings


def create_app() -> FastAPI:
    """
    Create and configure FastAPI application.

    Returns:
        Configured FastAPI application instance.
    """
    app = FastAPI(
        title=settings.APP_NAME,
       
---

## SonarQube & Security Vulnerability Skill (java, python, javascript, security, code-quality, sonarqube, owasp)

## 1. Common Security Vulnerabilities (OWASP Top 10)

### 1.1 SQL Injection — A03:2021

**Vulnerability:** Attacker injects SQL commands through user input.

```java
// ✗ VULNERABLE: String concatenation
String query = "SELECT * FROM orders WHERE customer_id = " + customerId;
ResultSet rs = stmt.executeQuery(query);
// Attack: customerId = "1 OR 1=1" → Returns all orders

// ✓ SECURE: Use parameterized queries
String query = "SELECT * FROM orders WHERE customer_id = ?";
PreparedStatement pstmt = connection.prepareStatement(query);
pstmt.setInt(1, customerId);
ResultSet rs = pstmt.executeQuery();
```plaintext

```python
# ✗ VULNERABLE: String formatting
query = f"SELECT * FROM orders WHERE customer_id = {customer_id}"
cursor.execute(query)
# Attack: customer_id = "1 OR 1=1" → Returns all orders

# ✓ SECURE: Use parameterized queries
query = "SELECT * FROM orders WHERE customer_id = %s"
cursor.execute(query, (customer_id,))
```plaintext

```typescript
// ✗ VULNERABLE: String concatenation in ORM
const orders = await Order.find(`WHERE customer_id = ${customerId}`);

// ✓ SECURE: Use ORM query builders
const orders = await Order.find({ where: { customerId } });
```plaintext

**SonarQube Rule:** `java:S2077` (SQL Injection), `python:S3649`, `typescript:S3649`

---

### 1.2 Cross-Site Scripting (XSS) — A03:2021

**Vulnerability:** Attacker injects malicious JavaScript that executes in users' browsers.

```javascript
// ✗ VULNERABLE: Direct innerHTML assignment
document.getElementById('output').innerHTML = userInput;
// Attack: userInput = "<img src=x onerror='steal credentials'>"

// ✓ SECURE: Use textContent for text, or sanitize HTML
document.getElementById('output').textContent = userInput;

// ✓ SECURE: If HTML is needed, use DOMPurify library
import DOMPurify from 'dompurify';
document.getElementById('output').innerHTML = DOMPurify.sanitize(userInput);
```plaintext

```typescript
// React: XSS example

// ✗ VULNERABLE: dangerouslySetInnerHTML without sanitization
<di
---

## Spring Framework Advanced Skill (java, spring, spring-boot, spring-webflux, spring-batch, spring-cloud, spring-security)

## 1. IoC Container — How It Really Works

Understanding the container lifecycle helps debug startup failures and bean wiring issues.

```java
Application starts
  → Reads @ComponentScan / @Bean / XML config
  → Creates BeanDefinition for each bean (metadata — not the instance yet)
  → Resolves dependencies between BeanDefinitions
  → Instantiates beans in dependency order
  → Injects dependencies (constructor → setter → field in that order)
  → Calls @PostConstruct methods
  → Application is ready

Application shuts down
  → Calls @PreDestroy methods
  → Destroys singletons in reverse creation order
```java

### Bean Scopes

```java
@Component
@Scope("singleton")    // default — one instance per application context
public class OrderService { }

@Component
@Scope("prototype")    // new instance every time it is requested from the context
public class OrderProcessor { }

// Web scopes — only valid in a web application context
@Component
@Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class RequestContext { }   // new instance per HTTP request

@Component
@Scope(value = WebApplicationContext.SCOPE_SESSION, proxyMode = ScopedProxyMode.TARGET_CLASS)
public class UserSession { }      // one instance per HTTP session
```java

### Conditional Beans

```java
/**
 * Creates the notification sender appropriate for the current environment.
 *
 * <p>In production: real email sender.
 * In test/dev: a stub that just logs — no real emails sent.</p>
 */
@Configuration
public class NotificationConfig {

    /**
     * Real email sender — only active when spring.mail.host is configured.
     * This means it won't try to connect to an SMTP server in dev/test.
     */
    @Bean
    @ConditionalOnProperty(name = "spring.mail.host")
    public NotificationSender emailNotificationSender(JavaMailSender mailSender) {
        return new EmailNotificationSender(mailSender);
    }

    /**
     * Stub sender — used when no mail host is con
---

## Spring Framework & Camel Integration Skill (java, apache-camel, spring-boot, spring-framework, integration)

## 1. Spring Boot Camel Starter

### 1.1 Maven Setup

```xml
<dependency>
    <groupId>org.apache.camel.springboot</groupId>
    <artifactId>camel-spring-boot-starter</artifactId>
    <version>4.0.0</version>
</dependency>

<dependency>
    <groupId>org.apache.camel.springboot</groupId>
    <artifactId>camel-spring-boot</artifactId>
    <version>4.0.0</version>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

### 1.2 Spring Boot Auto-Configuration

```java
/**
 * Spring Boot application with automatic Camel configuration.
 */
@SpringBootApplication
public class CamelSpringApplication {

    public static void main(String[] args) {
        SpringApplication.run(CamelSpringApplication.class, args);
    }

    /**
     * Customize Camel context.
     */
    @Bean
    public CamelContextConfiguration camelContextConfiguration() {
        return new CamelContextConfiguration() {
            @Override
            public void configureCamelContext(CamelContext camelContext) throws Exception {
                // Custom Camel configuration
                camelContext.setStreamCaching(true);
                camelContext.setTracing(false);
            }

            @Override
            public void onCamelContextStarted(CamelContext camelContext, boolean alreadyStarted) throws Exception {
                log.info("Camel context started with Spring Boot");
            }
        };
    }
}
```

---

## 2. Dependency Injection in Camel Routes

### 2.1 Using Spring Beans in Routes

```java
/**
 * Service to be injected into Camel routes.
 */
@Service
public class OrderProcessingService {

    private final OrderRepository orderRepository;
    private final PaymentService paymentService;

    public OrderProcessingService(OrderRepository orderReposito
---

## JUnit5 Testing Skill (java, junit5, testing, mockito, testcontainers, spring-boot)

## 1. Test Method Naming Convention

### 1.1 Given-When-Then (GWT) Pattern

```java
/**
 * Test class for OrderService with meaningful test names.
 *
 * Naming pattern: givenXxx_whenYyy_thenZzz()
 *   - givenXxx: Setup/precondition
 *   - whenYyy: Action being tested
 *   - thenZzz: Expected outcome
 */
@ExtendWith(MockitoExtension.class)
class OrderServiceTest {

    @InjectMocks
    private OrderService orderService;

    @Mock
    private OrderRepository orderRepository;

    @Mock
    private PaymentGateway paymentGateway;

    /**
     * Test: GIVEN a valid order exists | WHEN getOrderById is called | THEN return the order.
     */
    @Test
    @DisplayName("Given valid order exists, when fetching by ID, then return the order")
    void givenValidOrderExists_whenGetOrderById_thenReturnOrder() {
        // Arrange
        Long orderId = 123L;
        Order expectedOrder = Order.builder()
                .id(orderId)
                .customerId(456L)
                .status(OrderStatus.PENDING)
                .totalAmount(BigDecimal.valueOf(99.99))
                .build();

        when(orderRepository.findById(orderId)).thenReturn(Optional.of(expectedOrder));

        // Act
        Optional<Order> result = orderService.getOrderById(orderId);

        // Assert
        assertTrue(result.isPresent());
        assertEquals(expectedOrder.getId(), result.get().getId());
        assertEquals(expectedOrder.getStatus(), result.get().getStatus());
        verify(orderRepository, times(1)).findById(orderId);
    }

    /**
     * Test: GIVEN order doesn't exist | WHEN getOrderById is called | THEN throw exception.
     */
    @Test
    @DisplayName("Given order doesn't exist, when fetching by ID, then throw EntityNotFoundException")
    void givenOrderNotExists_whenGetOrderById_thenThrowException() {
        // Arrange
        Long orderId = 999L;
        when(orderRepository.findById(orderId)).thenReturn(Optional.empty());

        // Act & Assert
        assertThrow
---

## Pytest Testing Skill (python, pytest, fastapi, testing, async, mocking)

## 1. Test File Organization & Naming

### 1.1 Project Structure

```plaintext
project/
├── app/
│   ├── __init__.py
│   ├── models/
│   ├── schemas/
│   ├── services/
│   └── api/
│
├── tests/
│   ├── __init__.py
│   ├── conftest.py              # Shared fixtures
│   │
│   ├── unit/
│   │   ├── test_order_service.py
│   │   ├── test_payment_service.py
│   │   └── test_validators.py
│   │
│   ├── integration/
│   │   ├── test_order_repository.py
│   │   └── test_payment_gateway.py
│   │
│   ├── e2e/
│   │   ├── test_order_workflow.py
│   │   └── test_payment_flow.py
│   │
│   └── fixtures/
│       ├── orders.py            # Order test fixtures
│       └── payments.py          # Payment test fixtures
│
├── pytest.ini
└── requirements-dev.txt
```plaintext

### 1.2 Test Naming Convention

```python
"""
Test naming follows pattern: test_<unit>_<scenario>_<expected_result>
Also uses given_xxx_when_yyy_then_zzz pattern for clarity.
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from app.services.order_service import OrderService
from app.exceptions import EntityNotFoundException, ValidationException


class TestOrderService:
    """Test cases for OrderService."""

    def test_get_order_by_id_returns_order_when_found(self):
        """
        Test: GIVEN order exists in database | WHEN getOrderById called | THEN return order.
        """
        # Arrange
        order_id = 123
        expected_order = {"id": order_id, "customer_id": 1, "status": "PENDING"}

        order_service = OrderService(mock_db={"123": expected_order})

        # Act
        result = order_service.get_order_by_id(order_id)

        # Assert
        assert result == expected_order

    def test_get_order_by_id_raises_exception_when_not_found(self):
        """
        Test: GIVEN order doesn't exist | WHEN getOrderById called | THEN raise EntityNotFoundException.
        """
        # Arrange
        order_service = OrderService(mock_db={})

        # Act & Assert
        with
---

## React Testing Skill (react, javascript, testing, jest, react-testing-library, typescript)

## 1. Test File Organization & Naming

### 1.1 Project Structure

```plaintext
src/
├── components/
│   ├── OrderCard/
│   │   ├── OrderCard.tsx
│   │   ├── OrderCard.test.tsx      # Test file next to component
│   │   └── OrderCard.types.ts
│   │
│   ├── OrderForm/
│   │   ├── OrderForm.tsx
│   │   ├── OrderForm.test.tsx
│   │   └── OrderForm.types.ts
│   │
│   └── __tests__/
│       ├── integration/
│       │   └── OrderWorkflow.test.tsx
│       └── e2e/
│           └── OrderCreation.test.tsx
│
├── hooks/
│   ├── useOrders.ts
│   └── useOrders.test.ts            # Test file next to hook
│
└── __mocks__/
    ├── handlers.ts                   # MSW request handlers
    └── server.ts                      # Mock server setup
```jsx

### 1.2 Test Naming Convention

```typescript
/**
 * Test naming: describe('<Component>', () => { test('should <action>', ...) })
 * Also use: describe.given_xxx_when_yyy_then_zzz pattern
 */

import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import OrderCard from './OrderCard';

describe('OrderCard', () => {
  /**
   * Test: GIVEN valid order data | WHEN rendering | THEN display all fields.
   */
  it('should display order details when rendered with valid data', () => {
    // Arrange
    const mockOrder = {
      id: 1,
      customerId: 100,
      status: 'PENDING',
      totalAmount: 99.99,
      items: [
        { productId: 1, productName: 'Product A', quantity: 2, unitPrice: 25.00, subtotal: 50.00 }
      ],
      deliveryAddress: '123 Main St',
      createdAt: new Date('2026-04-03'),
    };

    // Act
    render(<OrderCard order={mockOrder} />);

    // Assert
    expect(screen.getByText('Order #1')).toBeInTheDocument();
    expect(screen.getByText('PENDING')).toBeInTheDocument();
    expect(screen.getByText('$99.99')).toBeInTheDocument();
    expect(screen.getByText('123 Main St')).toBeInTheDocument();
  });

  /**
   * Tes
---

