#!/usr/bin/env python3
"""MR/PR comment formatter for code review results. Converts review data to
scannable markdown with scorecard, critical issues (P0/P1), action items, and
report link."""

from __future__ import annotations

from typing import Any, Dict, List


class MRCommentFormatter:
    """Formats code review results as markdown MR/PR comments."""

    GRADE_STATUS = {
        "A": ("✅ Approved", "Approved"),
        "B": ("✅ Approved", "Approved"),
        "C": ("⚠️ Changes Needed", "Changes Needed"),
        "D": ("❌ Request Changes", "Request Changes"),
        "F": ("❌ Reject", "Reject"),
    }

    @staticmethod
    def format_comment(review_data: Dict[str, Any], report_path: str) -> str:
        """Format code review results as markdown MR/PR comment.

        Args:
            review_data: Dict with 'scorecard' (requirement, code_quality, testing,
                        documentation, final_grade, final_score) and 'issues' list
                        (category, severity, description, suggested_fix)
            report_path: Full path to generated HTML report

        Returns:
            str: Markdown comment with 7 sections: header, scorecard, grade, critical
                issues (P0/P1 only), action items (max 3), report link, footer

        Raises:
            ValueError: Missing 'scorecard' or 'issues'
            TypeError: Wrong parameter types
        """
        # Type validation
        if not isinstance(review_data, dict):
            raise TypeError(f"review_data must be dict, got {type(review_data)}")
        if not isinstance(report_path, str):
            raise TypeError(f"report_path must be str, got {type(report_path)}")

        # Validate required fields
        if "scorecard" not in review_data:
            raise ValueError("Missing required 'scorecard' in review_data")
        if "issues" not in review_data:
            raise ValueError("Missing required 'issues' in review_data")

        scorecard = review_data["scorecard"]
        issues = review_data.get("issues", [])

        # Extract scorecard metrics
        requirement = scorecard.get("requirement", 0)
        code_quality = scorecard.get("code_quality", 0)
        testing = scorecard.get("testing", 0)
        documentation = scorecard.get("documentation", 0)
        final_grade = scorecard.get("final_grade", "N/A")
        final_score = scorecard.get("final_score", 0)

        # Build comment sections
        sections = []

        # Section 1: Header
        sections.append("## 🔍 Code Review Complete")
        sections.append("")

        # Section 2: Scorecard
        sections.append("### Scorecard")
        sections.append(f"- **Requirement Met:** {requirement}%")
        sections.append(f"- **Code Quality:** {code_quality}%")
        sections.append(f"- **Test Coverage:** {testing}%")
        sections.append(f"- **Documentation:** {documentation}%")
        sections.append("")

        # Section 3: Final Grade
        status_emoji, status_text = MRCommentFormatter.GRADE_STATUS.get(
            final_grade, ("❓ Unknown", "Unknown")
        )
        sections.append(f"**Final Grade: {final_grade} ({final_score}/100)**")
        sections.append("")
        sections.append(f"**Status:** {status_emoji}")
        sections.append("")

        # Section 4: Critical Issues (P0/P1 only)
        critical_issues = [
            issue
            for issue in issues
            if issue.get("severity") in ["P0", "P1"]
        ]

        sections.append("### 🚨 Critical Issues (P0/P1)")
        sections.append("")

        if critical_issues:
            # Show max 5 critical issues
            for i, issue in enumerate(critical_issues[:5], 1):
                category = issue.get("category", "Unknown")
                severity = issue.get("severity", "P3")
                description = issue.get("description", "No description")
                sections.append(f"{i}. **[{category}] {severity}** — {description}")
        else:
            sections.append("No critical issues found ✓")

        sections.append("")

        # Section 5: Action Items (top 3 from critical issues or generic)
        sections.append("### ✅ Action Items Before Merge")
        sections.append("")

        action_items = MRCommentFormatter._extract_action_items(
            critical_issues, limit=3
        )
        for action in action_items:
            sections.append(f"- [ ] {action}")

        sections.append("")

        # Section 6: Report Link
        sections.append("### 📊 Full Analysis")
        sections.append("")
        sections.append(f"See detailed report: `{report_path}`")
        sections.append("")

        # Section 7: Footer
        sections.append("---")
        sections.append("_Review generated by Code Review Agent v3_")

        return "\n".join(sections)

    @staticmethod
    def _extract_action_items(
        critical_issues: List[Dict[str, Any]], limit: int = 3
    ) -> List[str]:
        """Extract action items from critical issues or use generic defaults.

        Args:
            critical_issues: P0/P1 issues list
            limit: Max items to return (default 3)

        Returns:
            List[str]: Action items from suggested_fix or generic defaults
        """
        action_items = []

        # Extract suggested fixes from critical issues
        for issue in critical_issues[:limit]:
            suggested_fix = issue.get("suggested_fix", "").strip()
            if suggested_fix:
                action_items.append(suggested_fix)

        # If we have fewer than 3 actions from issues, add generic ones
        generic_actions = [
            "Address critical security issues",
            "Improve test coverage for edge cases",
            "Add comprehensive documentation",
            "Fix performance bottlenecks",
            "Resolve design pattern violations",
        ]

        for generic_action in generic_actions:
            if len(action_items) >= limit:
                break
            if generic_action not in action_items:
                action_items.append(generic_action)

        # Ensure at least 3 items
        while len(action_items) < 3:
            action_items.append(f"Review item {len(action_items) + 1}")

        return action_items[:limit]


if __name__ == "__main__":
    test_data = {
        "scorecard": {
            "requirement": 95,
            "code_quality": 85,
            "testing": 70,
            "documentation": 60,
            "final_grade": "B",
            "final_score": 84.4,
        },
        "issues": [
            {"category": "Security", "severity": "P0", "description": "SQL injection",
             "suggested_fix": "Use parameterized queries"},
            {"category": "Testing", "severity": "P1", "description": "Missing tests",
             "suggested_fix": "Add error test cases"},
        ],
    }
    print(MRCommentFormatter.format_comment(
        test_data, "/reviews/review-PROJ-123-20260525T143022.html"))
