#!/usr/bin/env python3
"""Generate platform-specific configuration files with hook registrations.

This module provides ConfigGenerator for creating platform-native config files
that register hooks discovered by the exporter.

Example:
    config_gen = ConfigGenerator(repo_root)
    hooks = [HookFile(...), HookFile(...)]

    # Generate Claude settings
    settings = config_gen.generate_claude_settings(hooks)

    # Generate Copilot config
    copilot_config = config_gen.generate_copilot_config(hooks)
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class HookConfig:
    """Configuration for a hook in platform settings.

    Attributes:
        hook_type: Type of hook (e.g. 'pre-commit', 'user-prompt-submit')
        hook_path: Path to the hook script (relative or absolute)
    """
    hook_type: str
    hook_path: Path


class ConfigGenerator:
    """Generate platform-specific configuration files with hook registrations.

    This class creates platform-native config files (.claude/settings.json,
    .github/copilot.yml, etc.) that register discovered hooks for use by
    the respective AI assistant platforms.
    """

    def __init__(self, repo_root: Path) -> None:
        """Initialize ConfigGenerator.

        Args:
            repo_root: Root directory of the repository
        """
        self.repo_root = repo_root

    def generate_claude_settings(self, hooks: list[Any]) -> dict[str, Any]:
        """Generate .claude/settings.json with hook registrations.

        Creates a settings dictionary suitable for Claude Code's settings.json,
        with hooks organized by type (pre-commit, user-prompt-submit, etc).

        Args:
            hooks: List of HookFile objects from exporter

        Returns:
            Dict suitable for JSON serialization to .claude/settings.json
        """
        # Organize hooks by type
        hooks_by_type: dict[str, list[dict[str, str]]] = {}

        for hook in hooks:
            hook_type = hook.hook_type  # e.g. 'pre-commit', 'user-prompt-submit'

            if hook_type not in hooks_by_type:
                hooks_by_type[hook_type] = []

            # Get relative path from repo root to hook file
            try:
                hook_rel_path = hook.path.relative_to(self.repo_root)
            except ValueError:
                # Hook path is not relative to repo_root, use absolute
                hook_rel_path = hook.path

            hooks_by_type[hook_type].append({
                "type": "command",
                "command": str(hook_rel_path)
            })

        # Build settings structure
        settings = {
            "model": "haiku",
            "hooks": {},
            "enabledPlugins": {
                "superpowers@claude-plugins-official": True,
                "frontend-design@claude-plugins-official": True,
                "code-review@claude-plugins-official": True,
                "playwright@claude-plugins-official": True,
            }
        }

        # Map hook types to Claude settings hook categories
        # Claude settings uses specific hook category names
        hook_type_mapping = {
            "pre-commit": "PreCommit",
            "user-prompt-submit": "UserPromptSubmit",
            "post-commit": "PostCommit",
        }

        for hook_type, hook_list in hooks_by_type.items():
            # Get Claude hook category name, or use hook_type as-is
            category_name = hook_type_mapping.get(hook_type, hook_type)

            if category_name not in settings["hooks"]:
                settings["hooks"][category_name] = []

            settings["hooks"][category_name].extend(hook_list)

        return settings

    def generate_copilot_config(self, hooks: list[Any]) -> str:
        """Generate GitHub Copilot .github/copilot.yml config.

        Creates a YAML configuration file for GitHub Copilot that registers
        discovered hook scripts.

        Args:
            hooks: List of HookFile objects from exporter

        Returns:
            YAML config as string (ready to write to file)
        """
        lines = [
            "# Generated by tools/exporter.py — Do not edit manually",
            "# Re-run: python tools/exporter.py",
            "",
            "version: 1",
            "",
            "hooks:",
        ]

        for hook in hooks:
            hook_name = hook.slug

            # Get relative path from repo root
            try:
                hook_rel_path = hook.path.relative_to(self.repo_root)
            except ValueError:
                hook_rel_path = hook.path

            lines.append(f"  - name: {hook_name}")
            lines.append(f"    type: {hook.hook_type}")
            lines.append(f"    path: {hook_rel_path}")
            lines.append("")

        return "\n".join(lines)

    def generate_cursor_config(self, hooks: list[Any]) -> str:
        """Generate Cursor IDE .cursor/cursor.config.json with hook registrations.

        Args:
            hooks: List of HookFile objects from exporter

        Returns:
            JSON config as string
        """
        hooks_by_type: dict[str, list[dict[str, str]]] = {}

        for hook in hooks:
            hook_type = hook.hook_type

            if hook_type not in hooks_by_type:
                hooks_by_type[hook_type] = []

            try:
                hook_rel_path = hook.path.relative_to(self.repo_root)
            except ValueError:
                hook_rel_path = hook.path

            hooks_by_type[hook_type].append({
                "name": hook.slug,
                "path": str(hook_rel_path),
                "description": hook.description or f"{hook.slug} hook"
            })

        config = {
            "version": "1.0",
            "hooks": hooks_by_type
        }

        return json.dumps(config, indent=2)

    def generate_windsurf_config(self, hooks: list[Any]) -> str:
        """Generate Windsurf IDE .windsurf/hooks.json with registrations.

        Args:
            hooks: List of HookFile objects from exporter

        Returns:
            JSON config as string
        """
        hooks_list = []

        for hook in hooks:
            try:
                hook_rel_path = hook.path.relative_to(self.repo_root)
            except ValueError:
                hook_rel_path = hook.path

            hooks_list.append({
                "name": hook.slug,
                "type": hook.hook_type,
                "path": str(hook_rel_path),
                "description": hook.description or f"{hook.slug} hook"
            })

        config = {
            "version": "1.0",
            "hooks": hooks_list
        }

        return json.dumps(config, indent=2)
